### ISSUE TITLE
Replace LG Dialog with Bottom Sheet and Side Sheet

### ISSUE THREAD

**Issue by SidharthMudgil** [SidharthMudgil/lg-motion#4]
The current Liquid Galaxy connection dialog in our Android app presents some usability challenges on different device sizes. On mobile devices, the dialog shrinks when the keyboard is shown, affecting the user experience. To overcome this issue and provide consistent and optimal UI, we should replace the existing dialog with adaptive bottom sheets for mobile devices and side sheets for tablet devices.

**Comment by dharamveer-gupta** [comment]
Can you please label this issue as **`hactoberfest`**?

**Comment by SidharthMudgil** [comment]
the repository marked as hacktoberfest
